### ISSUE TITLE
As SFSCON organizer I want the SFSCON App and its backend running on NOI servers, to be completely independent from the service provider.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.sfscon.app#3]
Here the links to our current test deployments
**Web app** https://app.sfscon.testingmachine.eu
**Web admin App** https://webadmin.app.sfscon.testingmachine.eu/
**Backend** https://backend.app.sfscon.testingmachine.eu/

**Comment by dulvui** [comment]
The backend and frontend are now online and available here (credentials can be found in passbolt)
https://webadmin.app.sfscon.testingmachine.eu

I was also able to publish a first internal test for Android on the Google Play Store with the app using the backend hosted on our infrastructure. You should be able to download the new version from the Google Play Store, if not I can share you the latest APK file for manual install.

Now I can try to change the app to see how easy it is to manipulate the codebase. Probably I will try to remove the pretix tike code login to save the schedule and save it locally.

**Comment by dulvui** [comment]
And here the app as webapp
https://app.sfscon.testingmachine.eu
